links:
    - text: 'top'
      href: '/?page=top'
    - text: 'ブログ'
      href: '/?post'
    - text: '元サイト'
      href: 'https://aotake91.net'
    - text: '青竹倉庫'
      href: 'https://aotake91.yu-nagi.com'
    - text: '西鉄なんでもWiki'
      href: 'https://seesaawiki.jp/nishitetsu-fan/'
sociallinks:
    - icon: 'fa-twitter-square'
      href: 'https://twitter.com/aotake91'
    - icon: 'fa-github-square'
      href: 'https://github.com/gbamboo415'
