links:
    - text: 'top'
      href: '/?page=top'
    - text: 'ブログ'
      href: '/?post'
    - text: '外部サイト'
      href: './'
      sublinks:
        - text: '元サイト'
          href: 'https://aotake91.net'
        - text: '青竹倉庫'
          href: 'https://aotake91.yu-nagi.com'
        - text: '西鉄なんでもWiki'
          href: 'https://seesaawiki.jp/nishitetsu-fan/'
