protocol: 'https:'
host: 'blog.aotake91.net'
sitetitle: '青竹雑記帖(N)'
sitesubtitle: '青竹雑記帖、強化中。'
links:
- text: 'ブログ'
  href: '/?post'
- text: '青竹荘 (サークル活動サイト)'
  href: 'https://www.aotake91.net'
- text: '青竹倉庫'
  href: 'https://aotake91.yu-nagi.com'
- text: '西鉄なんでもWiki'
  href: 'https://seesaawiki.jp/nishitetsu-fan/'
- text: '西鉄終夜運転・正月ダイヤ（過去情報）'
  href: 'https://blog.aotake91.net/?nnr-newyear-allnight'
  sublinks:
  - text: '2015.12.31終夜運転運用表'
    href: 'https://blog.aotake91.net/?2015-12-31-allnight'
  - text: '西鉄終夜運転・正月ダイヤ2016'
    href: 'https://blog.aotake91.net/?nnr-newyear2016'
  - text: '西鉄終夜運転・正月ダイヤ2017'
    href: 'https://blog.aotake91.net/?nnr-newyear2017'
- text: '西鉄車両検査進行表'
  href: 'https://blog.aotake91.net/?nnr-car-inspect'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/aotake91'
- icon: 'fa-github-square'
  href: 'https://github.com/gbamboo415'
- icon: 'fa-amazon'
  href: 'https://www.amazon.jp/hz/wishlist/ls/2ZZ1APRQCKQBH?ref_=wl_share'
- icon: 'fa-instagram'
  href: 'https://www.instagram.com/aotake91/?hl=ja'
- icon: 'fa-mastodon'
  href: 'https://mstdn.aotake91.net'
hatena: 'true'
pocket: 'true'
twitter: 'aotake91'
line: 'true'
