protocol: 'https:'
host: 'blog.aotake91.net'
sitetitle: '青竹雑記帖(N)'
sitesubtitle: '青竹雑記帖、強化中。'
links:
    - text: 'ブログ'
      href: '/?post'
    - text: '元サイト'
      href: 'https://aotake91.net'
    - text: '青竹倉庫'
      href: 'https://aotake91.yu-nagi.com'
    - text: '西鉄なんでもWiki'
      href: 'https://seesaawiki.jp/nishitetsu-fan/'
sociallinks:
    - icon: 'fa-twitter-square'
      href: 'https://twitter.com/aotake91'
    - icon: 'fa-github-square'
      href: 'https://github.com/gbamboo415'
